version: '3.1'

services:

  db:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: tasks

  adminer:
    image: adminer
    ports:
      - 8080:8080
